### ISSUE TITLE
ORCT2 will not install to non-default user data directory

### ISSUE THREAD

**Issue by dlee13** [LRFLEW/OpenRCT2Launcher#1]
I have my Documents folder located on my D: drive, so my ORCT2 directory path is:
`D:\Derek\Documents\OpenRCT2`
However, the launcher always creates new folders and installs and tries to run ORCT2 at 
`C:\Users\Derek\Documents\OpenRCT2`

**Comment by LRFLEW** [comment]
Ok, I can see that there is likely a problem here, but I'm uncertain what exactly is going on. I don't use Windows often, and usually develop this on a virtual machine, so I haven't encountered this sort of error.

How exactly is that configured. I have never heard of having a user's folder not on the boot drive, so I didn't even know this could happen. I've also not hardcoded any sort of home folder path, and instead use QDir::homePath(), so any problems with this is likely stemming from that. I am willing to work around Qt's shortcomings (which I already have for a problem on OS X), but I don't exactly know the circumstances of this happening.

If you can explain how I could get my VM into the same situation, I can work on fixing this. (I can handle adding the virtual drive, I just don't know how to configure Windows to get it to do what you're describing).

**Comment by dlee13** [comment]
Open and Windows Explorer window and find your Documents folder. Right click it and get the Properties window. In the Location tab, put in the new path and Apply.

**Comment by LRFLEW** [comment]
I was able to replicate this bug, and I think I've found the solution after a little bit of searching. I hadn't realized this was possible, so I originally didn't account for it. I'll fix it in an upcoming update.

**Comment by dlee13** [comment]
Thank you.
