### ISSUE TITLE
New 0.0.5 install - portable and installer issue

### ISSUE THREAD

**Issue by cookins** [LRFLEW/OpenRCT2Launcher#11]
I installing game as usual through installer then setting install folder after shortcut launch - its saying:
cant find g1.dat in data folder - there only g2.dat by the way.
same with portable version.

**Comment by Gymnasiast** [comment]
Doesn't seem like a launcher issue to me. `g1.dat` is a file from RCT2 - you need to have it installed. It's also the RCT2 folder you have to select when asked for the install folder. By the look of it, you chose the OpenRCT2 folder.

**Comment by cookins** [comment]
the point is - in installer there no g1.dat - only g2.dat.
do i suppose to have mine g1.dat from original game? :-/

**Comment by Gymnasiast** [comment]
If you only see g2.dat you're looking at the wrong folder. You need to have the original game installed for its assets (graphic files, music, sound effects). Install it, and point to that folder when asked for the directory.

**Comment by cookins** [comment]
oh lol
i thought this is full game - cant say how much original game was required space.
pardon then..

**Comment by rawr51919** [comment]
Since this happens to be a misconception about the installer and nothing else, someone should close this issue.

**Comment by LRFLEW** [comment]
I'll go ahead and close this. However, I do think that this is indicative of a documentation problem. I need to update the readme (or create a usage readme) to help explain this probably.

**Comment by cookins** [comment]
just need to type it on download page - that original game data required! red letters - yeeesss!
