### ISSUE TITLE
Launcher won't launch

### ISSUE THREAD

**Issue by sp00pster** [LRFLEW/OpenRCT2Launcher#18]
This is most likely related to the new Windows 10 update, because today my background and N64 roms were also reset. The launcher won't launch anymore, upon trying i get [this error.](http://i.imgur.com/2bhORtL.png) I reinstalled it and opening it from the source still works, but the launcher just doesn't work.

**Comment by LRFLEW** [comment]
Please try downloading and installing the vc_redist.x86.exe installer at https://www.microsoft.com/en-us/download/details.aspx?id=48145

Let me know if that fixes the issue. The error suggests it's an issue of an old redistributable.

**Comment by sp00pster** [comment]
sorry for responding so late

It said I had already installed it, so I tried reinstalling it. I also reinstalled the launcher. And, it worked! I don't know which reinstallment fixed it, but it was probably the redistributable.
