### ISSUE TITLE
macOS Sierra: Unable to find RCT2 installation directory.

### ISSUE THREAD

**Issue by jaredjones** [LRFLEW/OpenRCT2Launcher#19]
0.0.5.0 build dd2178c

![screen shot 2016-08-05 at 5 42 07 pm](https://cloud.githubusercontent.com/assets/1316894/17453645/0bc06304-5b34-11e6-9b3e-aba4420fbaa1.png)

**Comment by LRFLEW** [comment]
Not an issue with the launcher. You need the RCT2 files installed somewhere, and use the file selector to tell OpenRCT2 where it's installed. There are multiple resources on how to do this, including [The OpenRCT2 Wiki](https://github.com/OpenRCT2/OpenRCT2/wiki/Installation-on-Linux#installing-the-game), [Reddit](https://www.reddit.com/r/openrct2/search?q=mac&restrict_sr=on&sort=relevance&t=all), or just ask for help on [non-dev gitter](https://gitter.im/OpenRCT2/OpenRCT2/non-dev).

Closing this as it isn't an issue (and also isn't the launcher).
