### ISSUE TITLE
Launcher has to be edited to make users able to download x64/64-bit builds

### ISSUE THREAD

**Issue by mrtnptrs** [LRFLEW/OpenRCT2Launcher#20]
Just a reminder for when the 64-bit builds are fully ready and build automaticly by AppVeyor. Maybe let the launcher find if the user is using a 32-bit or 64-bit OS and choose and ALSO make an option to let the user choose if he wants the 32 or 64-bit builds? (just like we do now with choosing branches.) What does @LRFLEW think about this?

**Comment by LRFLEW** [comment]
@mrtnptrs Keep in mind that I don't get the builds from AppVeyor, but from OpenRCT2.org. When the 64-bit builds start up, I'll contact Jarno and see about getting the API updated for it.

I'm not sure if it's been decided that there will be separate 32-bit and 64-bit builds. It's likely that the project will distribute just one or the other. If there are two different builds, then I'll have two different builds of the launcher as well, and will most likely tie the version downloaded to the version of the launcher. I can probably figure out if it's a 64-bit system at runtime, though.

However, this is not an issue _yet_. We'll see when it happens.

**Comment by GingerAdonis** [comment]
API shouldn't need much of an update if there will be separate builds. It'll simply be a different flavourId than the one currently used for 32-bit.

**Comment by Margen67** [comment]
64 bit builds are available now. https://openrct2.org/downloads/develop/latest

**Comment by IntelOrca** [comment]
Bump, they are now recommended as default download.

**Comment by LRFLEW** [comment]
Really? I think it's odd that you're making it the default, but ok.

@IntelOrca Are you planning on continuing supporting 32-bit or switch to 64-bit only in the near future?

**Comment by IntelOrca** [comment]
Continue to support 32-bit, you should check if the OS is 64-bit and use appropriate build

**Comment by mrtnptrs** [comment]
@IntelOrca But isn't it odd to recommend the 64-bit builds now, as much of the drawing code isn't done yet? Edit: sorry, clicked the wrong button.

**Comment by LRFLEW** [comment]
@mrtnptrs https://www.reddit.com/r/rct/comments/57nsez/openrct2_no_longer_uses_any_code_from_the/

**Comment by LRFLEW** [comment]
@IntelOrca 

> you should check if the OS is 64-bit and use appropriate build

I plan on going a separate route. Instead, I'll provide two versions of the launcher, one 32-bit and one 64-bit. I'll have the 32-bit launcher download the 32-bit game, and vice versa. It's easier for me, and allows for both to match.

**Comment by Margen67** [comment]
Can this be closed now?

**Comment by LRFLEW** [comment]
Yeah, I need to go through and close the issues v0.0.6 fixed. I'll start with this one. 😄
