### ISSUE TITLE
Launcher does not run game

### ISSUE THREAD

**Issue by PrinceDracus** [LRFLEW/OpenRCT2Launcher#23]
Downloaded both the installer and zipped folder for windows (10).  Installed to a custom folder on the desktop.  Ran the application (shortcut created from installer or created shortcut from main application, same thing) and failed to run.  Asked to select install directory for RCT2.  I have tried selecting both the install directory I chose in the installer and the bin file in the documents folder, but no matter what I use, the problem persists, stating that the game cannot find a certain file in that path.

**Comment by PrinceDracus** [comment]
Took some screenshots
![screenshot 1](https://cloud.githubusercontent.com/assets/22083520/18365061/16ea28bc-75df-11e6-9ed5-d71d66b56b46.png)
![screenshot 2](https://cloud.githubusercontent.com/assets/22083520/18365062/16edba68-75df-11e6-8504-ed389c67d548.png)

**Comment by Nubbie** [comment]
@PrinceDracus 
You need the game RCT2 installed too, that's the file it's refering to, do you have RCT2 installed?

**Comment by PrinceDracus** [comment]
Yea I realized that a while ago, I didn't have it on this PC.. thanks though :)
