### ISSUE TITLE
Launcher not loading version 1.2 Release

### ISSUE THREAD

**Issue by ghost** [LRFLEW/OpenRCT2Launcher#42]
Always end with error "Invalid Download". Development Updates working fine. Launcher version 0.0.7

![unbenannt](https://user-images.githubusercontent.com/39203895/39948936-87f3dcc2-5578-11e8-800b-f554bbc99dd1.PNG)

**Comment by LRFLEW** [comment]
Tested this, and I can reproduce the issue on both Windows and macOS (probably happens with Linux as well). Looking at it using the debugger, it appears that the openrct2.org api is reporting bad data, indicating a bad download. @JarnoVgr can you take a look at the release builds? I remember you had to manually add the builds, so could you check the metadata?

**Comment by GingerAdonis** [comment]
Will look into it asap

**Comment by GingerAdonis** [comment]
Should work again. (didn't test)

I've manually corrected the file sizes and SHA256 sum's.

**Comment by ghost** [comment]
It's working again, thanks for help!
