### ISSUE TITLE
Error Launching v0.2.5

### ISSUE THREAD

**Issue by koverr** [LRFLEW/OpenRCT2Launcher#53]
With the most recent openRCT2 update the launcher seems to have broken for me.
I had options set to the Develop branch, which upon opening returned "Error extracting archive". On first attempt, changing to the release branch worked and allowed the game to start, but after the first time, even release branch returned "Unable to Launch Game" when I hit play. I uninstalled and reinstalled to the same issues, but this time it never launched with the release branch. I can download the latest release of ORCT2 and open it and the game without issue, so it seems the Launcher is encountering a problem. Any thoughts?

**Comment by NoudL** [comment]
Looks like the develop build download for windows and mac are broken/deleted

**Comment by koverr** [comment]
If that’s the case, I’m curious how that would effect the launcher from pulling the release version.
